alias cp="cp -i"
alias df="df -h"
alias emacs="emacs -nw"
alias g="git"
alias juno="jupyter-notebook"
alias l="ls -lahFG"
alias p="python3"
alias reload="source ~/.bash_profile"
alias _="sudo"
alias t="tree -aC"
alias top="htop"

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias -- -="cd -"
